version: "2"
services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: online_market_db
    ports:
      - 3308:3306
    volumes:
      - ./database/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
      - online-market:/var/lib/mysql
      


volumes:
  online-market: